upgrade sentry-go and errors dependencies
sumup/sentrywriter pull request #1
Opened 2021-07-18 12:08 UTC by carole-lavillonniere

Upgrade dependencies to latest versions

2021-07-20 12:04 UTC, ndk requested changes

2021-07-20 12:04 UTC, ndk commented on example/go.mod
> -module github.com/mec07/sentrywriter/example
You don't need it. In the repository where you're gonna use it you can add `replace github.com/mec07/sentrywriter => github.com/sumup/sentrywriter` into `go.mod`.

2021-07-20 12:46 UTC, ndk approved these changes

2021-07-20 16:45 UTC, ndk approved these changes

2021-07-21 10:19 UTC, ndk approved these changes

2021-07-26 04:51 UTC, rosspatil approved these changes

2021-07-26 14:07 UTC, merged